apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  # base64
  POSTGRES_USER: YWRtaW4=  # admin
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  JWT_SECRET: c2VjcmV0  # secret
